project:
  type: website
  output-dir: docs

website:
  title: "Reproducible R"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Set up"
        href: setup.html
      - text: "1. Projects"
        href: 01_projects.html
      - text: "2. Version control"
        href: 02_version-control.html
      - text: "3. Code"
        href: 03_code.html
      - text: "4. Dependencies"
        href: 04_dependencies.html
      - text: "5. Publishing"
        href: 05_publishing.html
      - text: "Resources"
        href: resources.html